FINANCIAL_ASPECTS = [
    "Earnings and Revenue",
    "Market Performance",
    "Company Announcements",
    "Macroeconomic Indicators",
    "Analyst Recommendations",
    "Industry Trends",
    "Regulatory Environment",
    "Mergers and Acquisitions",
    "Dividends and Buybacks",
    "Competitor Analysis",
    "Technological Advancements",
    "Debt and Financial Stability",
    "Consumer Confidence",
    "Global Events",
    "Corporate Governance",
    "Innovation and Research & Development",
    "Environmental, Social, and Governance (ESG) Factors",
    "Crisis Management",
]

MOVIE_ASPECTS = [
    "Plot",
    "Characters",
    "Dialogue",
    "Cinematography",
    "Direction",
    "Soundtrack/Music",
    "Visual Effects",
    "Pacing",
    "Genre Suitability",
    "Originality",
    "Emotional Impact",
    "Cultural Representation",
    "Social Commentary",
    "Humor",
    "Ending/Resolution",
]